packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/dashboard/card/config.ts
packages/frontend/src/components/dashboard/card/human.tsx
packages/frontend/src/components/dashboard/card/issue.tsx
packages/frontend/src/components/dashboard/card/skeleton.tsx
packages/frontend/src/components/dashboard/card/tooltip.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/open/index.tsx
packages/frontend/src/components/open/search.tsx
packages/frontend/src/components/open/selected.tsx

[[議會透視板] 首頁-前端
](https://www.notion.so/twreporter/1818dbdca9328049a7ddcf363d1dc6e7?pvs=4)
N/A

fix(frontend): add `tooltip`, `note`, `skeleton`

---

packages/cms/CHANGELOG.md
packages/cms/lists/CommitteeMember.ts
packages/cms/lists/LegislativeYuanMember.ts
packages/cms/lists/Speech.ts
packages/cms/lists/Topic.ts
packages/cms/lists/index.ts
packages/cms/package.json
packages/cms/schema.graphql
packages/cms/schema.prisma

fix defects from multiple cards
因為 `monorepo` 底下各個 `packages` 所用到的 react & next 版本不同，所以需要指定該 package 自己使用的版本
挺神奇的

fix(cms): list order and label name and dependency for cms

---

package.json
packages/cms/package.json
packages/frontend/.eslintignore
packages/frontend/CHANGELOG.md
packages/frontend/eslint.config.mjs
packages/frontend/package.json
packages/shared/package.json
packages/shared/src/constants/legislative-yuan-member.ts
packages/shared/tsconfig.cjs.json
packages/shared/tsconfig.esm.json
packages/shared/tsconfig.json
yarn.lock

- (frontend): docker build failed
- (shared): also add typeRoot for tsconfig
N/A

fix: missing eslint config file

---

package.json
packages/cms/CHANGELOG.md
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/shared/package.json
yarn.lock

- use yarn v4 in all packages
- no hoist `cms` package
- add `shared` in workspace
- auto build after install
N/A

chore: update monorepo related config

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/footer/link.tsx
packages/frontend/src/components/footer/logo.tsx

fix(frontend): fix import type and footer prop type

---

packages/cms/CHANGELOG.md
packages/cms/lists/ImportRecord.ts
packages/cms/lists/views/upload-csv-input.tsx
packages/cms/package.json

[[change spec]立法委員匯入資料 ImageLink 應為非必填](https://www.notion.so/twreporter/change-spec-ImageLink-1ac8dbdca93280559993e9e82af86fa5?pvs=4)

feat(cms): required fields for upload csv

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/dashboard/card/human.tsx
packages/frontend/src/components/dashboard/card/issue.tsx
packages/frontend/src/components/dashboard/card/skeleton.tsx
packages/frontend/src/components/dashboard/function-bar/filter-modal.tsx
packages/frontend/src/components/dashboard/function-bar/index.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/header/index.tsx
packages/frontend/src/components/open/index.tsx
packages/frontend/src/components/open/search.tsx
packages/frontend/src/contexts/scroll-context.tsx
packages/frontend/src/styles/z-index.ts

[defects in [議會透視板] 首頁-前端](https://www.notion.so/twreporter/1818dbdca9328049a7ddcf363d1dc6e7?pvs=4)
N/A

fix: styles defects in dashboard page

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/hamburger-menu/index.tsx
packages/frontend/src/components/header/index.tsx

[[議會透視板] header 新增搜尋 bar - 前端](https://www.notion.so/twreporter/header-bar-1a48dbdca9328093adadd7dccfbec3ba?pvs=4)
N/A

feat: add search bar to header & hamburger menu

---

packages/frontend/.storybook/preview.ts
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/dashboard/card/config.ts
packages/frontend/src/components/dashboard/card/human.tsx
packages/frontend/src/components/dashboard/card/issue.tsx
packages/frontend/src/components/dashboard/function-bar/index.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/open/search.tsx
packages/frontend/src/components/sidebar/card.stories.ts
packages/frontend/src/components/sidebar/card.tsx
packages/frontend/src/components/sidebar/config.ts
packages/frontend/src/components/sidebar/followMore.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.stories.ts
packages/frontend/src/components/sidebar/tab.tsx
packages/frontend/src/components/sidebar/titleSection.stories.ts
packages/frontend/src/components/sidebar/titleSection.tsx
packages/frontend/src/components/skeleton.tsx
packages/frontend/src/styles/cheetsheet.ts
yarn.lock

[[議會透視板] 首頁側欄-前端](https://www.notion.so/twreporter/1a48dbdca93280918981dba55c856c58?pvs=4)
- todo: use correct icons when they deployed on npm package
https://github.com/twreporter/twreporter-npm-packages/pull/615

feat: add sidebar components & stories

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/sidebar/config.ts
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.tsx

build failed [log](https://console.cloud.google.com/cloud-build/builds;region=asia-east1/8f749d30-27f3-4dbc-bb7b-068d04c111b7;step=1?inv=1&invt=AbsWeg&project=coastal-run-106202)

fix(frontend): build failed problem

---

packages/frontend/.env.development
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/api/graphql/keystone.ts
packages/frontend/src/app/api/graphql/route.ts
packages/frontend/src/app/api/graphql/token.ts
packages/frontend/src/components/dashboard/function-bar/filter-modal.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/fetchers/party.ts
yarn.lock

[[議會透視板] 串接基礎工程](https://www.notion.so/twreporter/1978dbdca93280839d50daac918037b2?pvs=4)
- fetch api to retieve party data in filter modal
N/A

feat: add `/api/graphql` endpoint

---

packages/frontend/.env.development
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/api/graphql/route.ts

- cloud build failed ([log](https://console.cloud.google.com/cloud-build/builds;region=asia-east1/07295414-233e-46a9-b208-87f7b775fa05?inv=1&invt=AbscDg&project=coastal-run-106202))
N/A

fix: error is of type unknow & update env file

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/fetchers/party.ts

cloud build failed ([log](https://console.cloud.google.com/cloud-build/builds;region=asia-east1/894c8741-ebb8-438a-8254-44d9cb05b682?inv=1&invt=AbscQA&project=coastal-run-106202))
N/A

fix: `party` type incorrect

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/sidebar/config.ts
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.tsx
packages/frontend/src/components/sidebar/titleSection.tsx

[[defect] 3/19 側邊欄 UI 調整](https://www.notion.so/twreporter/defect-3-19-UI-1bb8dbdca93280ff9918e05fbe3fe289?pvs=4)
N/A

fix(frontend): fix sidebar style defects

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/button/pill-button.stories.tsx
packages/frontend/src/components/dashboard/card/human.tsx
packages/frontend/src/components/dashboard/function-bar/filter-modal.tsx
packages/frontend/src/components/dashboard/function-bar/index.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.tsx
packages/frontend/src/components/sidebar/titleSection.tsx

- fix defects in [[議會透視板] 首頁側欄-前端](https://www.notion.so/twreporter/1a48dbdca93280918981dba55c856c58?pvs=4)
- calculate sidebar gap when opening
- fix style defects
N/A

fix: defects

---

packages/cms/CHANGELOG.md
packages/cms/package.json

chore(cms): bump version to 0.0.2

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore: bump version to v0.0.3-beta.4

---

packages/frontend/CHANGELOG.md
packages/frontend/Dockerfile
packages/frontend/package.json

extend fetch timeout to 30000ms

chore: bump version to v0.0.3-beta.5

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/fetchers/server/legislator.ts
packages/frontend/src/fetchers/topic.ts

Add an abort signal to the fetch request to resolve timeout issues.

chore: bump version to v0.0.3-beta.6

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/fetchers/server/legislative-meeting.ts
packages/frontend/src/fetchers/server/legislator.ts

try to solve connection timeout error when fetching data in SSR
N/A

fix(frontend): fetch data with localhost in SSR

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/api/graphql/keystone.ts
packages/frontend/src/app/api/graphql/route.ts
packages/frontend/src/fetchers/server/legislative-meeting.ts
packages/frontend/src/fetchers/server/legislator.ts

try to fix connection error when fetching data in SSR
N/A

fix(frontend): use `keystoneFetch` in SSR

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/api/graphql/keystone.ts
packages/frontend/src/app/api/graphql/route.ts
packages/frontend/src/fetchers/server/legislative-meeting.ts
packages/frontend/src/fetchers/server/legislator.ts

try to fix connection timout error in SSR fetching
https://github.com/vercel/vercel/issues/11692#issuecomment-2171172148
N/A

fix(frontend): SSR req close connenction direclty 

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/sidebar/filter-modal/select-tag.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/skeleton.tsx

fix defect in [[defect] 側邊欄篩選調整項目*5
](https://www.notion.so/twreporter/defect-5-1d18dbdca93280999ffaf49b434c8f0b?pvs=4) & [[議會透視板]首頁-前端-優化*6](https://www.notion.so/twreporter/6-1b28dbdca9328004ae18c4a0772250aa?pvs=4)
N/A

fix(frontend): defects in sidebar filter modal

---

.github/workflows/frontend-build-check.yml

create build check for frontend
need to add `required status checks` at github repo settings

chore: add frontend build check workflow

---

.github/workflows/frontend-build-check.yml

enable corepack for yarn at workflow

fix: enable corepack for yarn at workflow

---

.github/workflows/frontend-build-check.yml
packages/cms/package.json
packages/frontend/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
yarn.lock

try to fix gitflow error when `yarn install` in #60 
N/A

chore: update shared version

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/dashboard/index.tsx

- use different gap in different viewport (defects in this [ticket](https://www.notion.so/twreporter/2-1b28dbdca9328004ae18c4a0772250aa?pvs=4))
N/A

fix(frontend): sidebar gap rwd

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore(frontend): bump version to v0.0.3

---

packages/cms/CHANGELOG.md
packages/cms/Dockerfile
packages/cms/package.json

use multi stage for docker build

chore(cms): bump version to 0.0.3-beta.2

---

packages/cms/CHANGELOG.md
packages/cms/Dockerfile
packages/cms/package.json

chore(cms): bump version to 0.0.3-beta.3

---

packages/cms/CHANGELOG.md
packages/cms/Dockerfile
packages/cms/package.json

[build fail](https://console.cloud.google.com/cloud-build/builds;region=asia-east1/a7ad9bd7-edca-4649-a478-0db58dafd5cf?project=coastal-run-106202)

fix(cms): install all dependencies for docker image

---

packages/shared/package.json

chore(shared): move tsup to dependencies

---

packages/cms/CHANGELOG.md
packages/cms/Dockerfile
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
yarn.lock

update @twreporter/congress-dashboard-shared and reset Dockerfile

chore(cms): update @twreporter/congress-dashboard-shared version

---

package.json
packages/cms/CHANGELOG.md
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
yarn.lock

postinstall at root package.json & update shared package

chore: use latest shared package

---

packages/shared/CHANGELOG.md
packages/shared/package.json

chore(shared): bump version to v0.0.4

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
yarn.lock

chore(frontend): bump version to v0.0.4

---

packages/frontend/.env.staging.public
packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore(frontend): bump version to v1.0.0-rc.1

---

packages/cms/CHANGELOG.md
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/shared/CHANGELOG.md
packages/shared/package.json
yarn.lock

chore: sync master

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/sidebar/filter-modal/index.tsx

[[議會透視板] 篩選工具的snackbar](https://www.notion.so/twreporter/snackbar-1d58dbdca9328099aab4f1f2b572d16c?pvs=4)

feat(frontend): add snackbar for sidebar filter

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/lawmaker/[slug]/page.tsx
packages/frontend/src/components/layout/speech-summary-list/layout.tsx
packages/frontend/src/components/legislator/index.tsx
packages/frontend/src/components/legislator/legislator-info.tsx
packages/frontend/src/components/legislator/legislator-list.tsx
packages/frontend/src/components/legislator/styles.ts
packages/frontend/src/components/loader/index.tsx
packages/frontend/src/components/sidebar/card.tsx
packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/topic/index.tsx
packages/frontend/src/components/topic/styles.ts
packages/frontend/src/components/topic/topic-list.tsx
packages/frontend/src/fetchers/legislative-meeting.ts
packages/frontend/src/fetchers/server/legislator.ts
packages/frontend/src/fetchers/server/topic.ts
packages/frontend/src/hooks/use-filters.ts
packages/frontend/src/utils/validate-meeting-params.ts

[[議會透視板]立委獨立頁-前端+串接+CMS新增欄位](https://www.notion.so/twreporter/CMS-1b98dbdca932805f8d06dd9ef68cf1be?pvs=4) defects
[[議會透視板]議題獨立頁-前端+串接+CMS新增欄位](https://www.notion.so/twreporter/CMS-1b98dbdca93280c4845cf7de2e8bf16b?pvs=4) defects

fix(frontend): legislator image & scrollbar width

---

packages/cms/CHANGELOG.md
packages/cms/environment-variables.ts
packages/cms/lists/Topic.ts
packages/cms/lists/views/related-article/index.tsx
packages/cms/migrations/20250429113608_add_topic_related_twreporter_articles/migration.sql
packages/cms/package.json
packages/cms/schema.graphql
packages/cms/schema.prisma
packages/frontend/.env.dev.public
packages/frontend/CHANGELOG.md
packages/frontend/next.config.ts
packages/frontend/package.json
packages/frontend/src/components/skeleton.tsx
packages/frontend/src/components/topic/index.tsx
packages/frontend/src/components/topic/styles.ts
packages/frontend/src/components/topic/topic-related-articles.tsx
packages/frontend/src/fetchers/server/topic.ts
packages/frontend/src/fetchers/twreporter-article.ts
packages/frontend/src/utils/date-formatters.ts

[[議會透視板]議題獨立頁-相關文章區塊-前端+串接](https://www.notion.so/twreporter/1c08dbdca932809d9168f4055d68e439?pvs=4)
https://github.com/twreporter/kubernetes-config/pull/71

feat: add related twreporter articles for topic page

---

.github/workflows/frontend-build-check.yml
packages/cms/.env.dev.public
packages/cms/CHANGELOG.md
packages/cms/environment-variables.ts
packages/cms/package.json

client side cannot read process.env set on runtime
N/A

fix(cms): add `NEXT_PUBLIC` for public env

---

packages/cms/CHANGELOG.md
packages/cms/environment-variables.ts
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/page.tsx

client env should be included in build time. Before resolving env problem, use staging branch value for tesing.
N/A

fix(cms): update default value of twreporter url

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/legislator/legislator-list.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.stories.ts
packages/frontend/src/components/sidebar/tab.tsx
packages/frontend/src/components/sidebar/title-section.stories.ts
packages/frontend/src/components/sidebar/title-section.tsx
packages/frontend/src/components/topic/topic-list.tsx

topic tab should not show fallback avatar
N/A

fix(frontend): add `showAvatar` props to Tab

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/page.tsx
packages/frontend/src/components/error/index.tsx
packages/frontend/src/components/error/type.ts

print error on UI to figure out what's going on
N/A

fix(frontend): add Error for SSR error

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/page.tsx
packages/frontend/src/fetchers/server/legislative-meeting.ts

add more logs to see which fetch failed
N/A

fix(frontend): add more log for home page SSR

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/error.tsx
packages/frontend/src/app/page.tsx
packages/frontend/src/components/error/type.ts

use error handling suggest in next doc ([ref](https://nextjs.org/docs/app/getting-started/error-handling))
N/A

fix(frontend): use app router way error handling

---

packages/cms/CHANGELOG.md
packages/cms/lists/views/related-article/index.tsx
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/topic/topic-related-articles.tsx

fix defects in [[議會透視板]議題獨立頁-相關文章區塊-前端+串接
](https://www.notion.so/twreporter/1c08dbdca932809d9168f4055d68e439?pvs=4)
N/A

fix: defects of twreporter related articles

---

packages/cms/CHANGELOG.md
packages/cms/lists/ImportRecord.ts
packages/cms/lists/views/uploader-field/index.tsx
packages/cms/package.json

[[defect] CMS修改-議題匯入](https://www.notion.so/twreporter/defect-CMS-1eb8dbdca9328042bfa0d1fdf70faeca?pvs=4)

fix(cms): use connect instead of set for create relationship

---

packages/shared/CHANGELOG.md
packages/shared/package.json

chore(shared): bump version to v0.0.6

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/footer/index.tsx
packages/frontend/src/components/speech/speech-aside-info.tsx

[[spec change] 無列席質詢對象時，隱藏該區塊](https://www.notion.so/twreporter/spec-change-1ee8dbdca9328004b3b5c4d5694d722f?pvs=4)

fix(frontend): hide attendee & topic if empty

---

packages/frontend/src/app/layout.tsx
packages/frontend/src/components/dashboard/card/human.tsx
packages/frontend/src/components/dashboard/card/issue.tsx
packages/frontend/src/components/dashboard/card/party-tag.tsx
packages/frontend/src/components/dashboard/card/tooltip.tsx
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/dashboard/type.ts
packages/frontend/src/components/legislator/legislator-list.tsx
packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/sidebar/follow-more.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/skeleton.tsx
packages/frontend/src/components/topic/topic-list.tsx
packages/frontend/src/fetchers/legislator.ts
packages/frontend/src/styles/z-index.ts
packages/frontend/src/utils/rwd.ts

[[defect] 0512首頁調整](https://www.notion.so/twreporter/defect-0512-1ee8dbdca93280efb852caacee96920c?pvs=4)
[[議會透視板-優化] 圓形立委照片顯示調整](https://www.notion.so/twreporter/1ee8dbdca932801fb012ce9743df6788?pvs=4)
[[議會透視板]首頁-前端-優化*1](https://www.notion.so/twreporter/1-1b28dbdca9328004ae18c4a0772250aa?pvs=4)
N/A

fix(frontend): address defects in home page

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/legislator/hooks/use-legislator-data.ts
packages/frontend/src/components/legislator/legislator-list.tsx
packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/topic/hooks/use-topic-data.ts
packages/frontend/src/components/topic/topic-list.tsx

[[defect] 0512議題／立委獨立頁調整](https://www.notion.so/twreporter/defect-0512-1ee8dbdca93280d3a4aad62b5e222048?pvs=4)

fix(frontend): topic and legislator page sidebar filter

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/components/legislator/legislator-list.tsx

[[defect] 0512議題／立委獨立頁調整](https://www.notion.so/twreporter/defect-0512-1ee8dbdca93280d3a4aad62b5e222048?pvs=4)

fix(frontend): legislator page follow more scroll no padding

---

packages/frontend/src/components/dashboard/function-bar/index.tsx
packages/frontend/src/fetchers/legislator.ts

[[defect] 首頁串接篩選器問題x3](https://www.notion.so/twreporter/defect-x3-1ee8dbdca93280d79b08ff6463ff7355?pvs=4)
N/A

fix(frontend): fix functionBar filter modal defect

---

packages/frontend/src/components/feedback/choose-feedback-type.tsx
packages/frontend/src/components/feedback/content-info.tsx
packages/frontend/src/components/feedback/index.tsx
packages/frontend/src/components/feedback/product-info.tsx
packages/frontend/src/components/feedback/style.ts
packages/frontend/src/components/topic/topic-feedback.tsx

fix defects in [[議會透視板]問題回報功能](https://www.notion.so/twreporter/1cf8dbdca932805d8ff2fc6be62a172a?pvs=4)
N/A

fix(frontend): address defects of Feedback

---

packages/frontend/next.config.ts
packages/frontend/src/app/page.tsx
packages/frontend/src/components/dashboard/card/issue.tsx
packages/frontend/src/components/dashboard/empty-state.tsx
packages/frontend/src/components/dashboard/hook/use-topic.ts
packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/image-with-skeleton.tsx
packages/frontend/src/components/legislator/legislator-info.tsx
packages/frontend/src/components/legislator/legislator-list.tsx
packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/sidebar/filter-modal/select-tag.tsx
packages/frontend/src/components/sidebar/follow-more.tsx
packages/frontend/src/components/sidebar/index.tsx
packages/frontend/src/components/sidebar/tab.tsx
packages/frontend/src/components/skeleton.tsx
packages/frontend/src/components/topic/topic-list.tsx
packages/frontend/src/components/topic/topic-related-articles.tsx
packages/frontend/src/fetchers/legislator.ts
packages/frontend/src/fetchers/server/topic.ts
packages/frontend/src/fetchers/topic.ts
packages/frontend/src/styles/cheetsheet.ts

fix defects in [[defect] 首頁串接篩選器問題*1](https://www.notion.so/twreporter/defect-1-1ee8dbdca93280d79b08ff6463ff7355?pvs=4), [[報導者觀測站-優化] 圓形立委照片顯示調整](https://www.notion.so/twreporter/1ee8dbdca932801fb012ce9743df6788?pvs=4), [[defect] 0519首頁修正](https://www.notion.so/twreporter/defect-0519-1f58dbdca932805a960dc083ed46df72?pvs=4), [[defect] 0512首頁調整*2](https://www.notion.so/twreporter/defect-0512-2-1ee8dbdca93280efb852caacee96920c?pvs=4)
N/A

fix(frontend): address defects in home page & sidebar

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore(frontend): bump version to v1.0.0-rc.20

---

packages/cms/.env.dev.public
packages/cms/CHANGELOG.md
packages/cms/environment-variables.ts
packages/cms/lists/views/related-article/index.tsx
packages/cms/lists/views/related-article/util.ts
packages/cms/package.json

[[報導者觀測站] cms public env](https://www.notion.so/twreporter/cms-public-env-1f88dbdca932808cb266f79e0c1e3b37?source=copy_link)
N/A

fix(cms): read public config in runtime

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json
packages/frontend/src/app/error.tsx
packages/frontend/src/app/loading.tsx
packages/frontend/src/app/not-found.tsx

[[議會透視版] 404畫面](https://www.notion.so/twreporter/404-1f98dbdca93280aeb3d3e182dc6827e1?pvs=4)
[[議會透視板] SSR error page](https://www.notion.so/twreporter/SSR-error-page-1e78dbdca93280ec8ee6e2d9e2c002b1?pvs=4)

feat(frontend): add not found page

---

packages/frontend/src/components/dashboard/hook/use-legislator.ts
packages/frontend/src/components/dashboard/index.tsx

[[defect] 首頁串接篩選器問題*1](https://www.notion.so/twreporter/defect-1-1ee8dbdca93280d79b08ff6463ff7355?source=copy_link)
N/A

fix(frontend): calculate load more

---

packages/cms/CHANGELOG.md
packages/cms/extend-graphql-schemas/index.ts
packages/cms/extend-graphql-schemas/recent-speech-topic-stats.ts
packages/cms/extend-graphql-schemas/top-n-topics-of-legislators.ts
packages/cms/extend-graphql-schemas/topics-order-by-speech-count.ts
packages/cms/keystone.ts
packages/cms/lists/Speech.ts
packages/cms/migrations/20250518164857_update_updated_at_of_speech_list/migration.sql
packages/cms/package.json
packages/cms/schema.graphql
packages/cms/schema.prisma
packages/cms/types/context.ts
yarn.lock

為支援 Algolia 搜尋，我們需每日同步以下資料：
1. **每位立委的最新一筆發言時間**
2. **各立委針對某主題的發言次數與最新發言時間**
3. **當日所有逐字稿資料（speeches）**
本 PR 新增 `recentSpeechTopicStats` Custom GQL Query，供 cronjob 每日擷取上述資料的第二點和第三點，並同步至 Algolia。
---
* 新增 GraphQL query：`recentSpeechTopicStats`
* 參考現有的 `topicsOrderBySpeechCount` 與 `topNTopicsOfLegislators` 實作邏輯
* Query 支援參數：
* `updatedAfter`: 只取擁有該日期之後更新的 speeches 的 topics
* `take`, `skip`, `cursor`: 支援 pagination
```graphql
query Query($take: Int, $skip: Int, $after: CalendarDay, $cursor: ID, $debug: Boolean) {
recentSpeechTopicStats(take: $take, skip: $skip, after: $after, cursor: $cursor, debug: $debug) {
speeches {
id
sessionTerm
meetingTerm
title
date
}
topics {
distinctMemberCount
members {
name
memberId
count
}
topicInfo {
id
slug
title
lastSpeechAt
sessionTerm
meetingTerm
} 
}
}
} …
```

feat(cms): custom GQL schema and resovler for querying what Algolai search needs

---

.github/workflows/frontend-build-check.yml

try to fix changeset workflow failed on frontend build check problem ([failed workflow link](https://github.com/twreporter/congress-dashboard-monorepo/actions/runs/15844051856/job/44662066956))
N/A

ci: skip frontend build on changeset PR

---

.github/workflows/dev-beta-release.yml
.github/workflows/release-production.yml
.github/workflows/staging-sync.yml

chore: update npm authentication method in CI workflows

---

.changeset/blue-laws-dress.md
.changeset/every-emus-hunt.md
packages/cms/environment-variables.ts
packages/cms/lists/ImportRecord.ts
packages/cms/lists/fields/uploader.ts
packages/cms/lists/views/related-article/index.tsx
packages/cms/lists/views/related-article/util.ts
packages/cms/schema.graphql

[[報導者觀測站] CMS資料匯入-相關文章](https://www.notion.so/twreporter/CMS-1fc8dbdca93280f4aedef284d9a23d93?source=copy_link)
list component is server component, cannot get browser `window` content, thus we should add its value in env
N/A

feat(cms): add import related articles

---

.changeset/bumpy-games-sleep.md
packages/frontend/src/components/header/index.tsx
packages/frontend/src/components/sidebar/style.ts

[[defect] UI優化調整*2](https://www.notion.so/twreporter/defect-UI-2-21e8dbdca93280938208d4a013a8e26f?source=copy_link)

fix(frontend): fix header logo and side bar link hover style

---

.changeset/pre.json
packages/cms/CHANGELOG.md
packages/cms/package.json
packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore(frontend): test v1.1.0-rc.5 on staging

---

.changeset/quiet-beers-hang.md
packages/cms/lists/ImportRecord.ts
packages/cms/lists/views/uploader-field/index.tsx
packages/cms/schema.graphql
packages/cms/schema.prisma

[[報導者觀測站-優化]資料匯入](https://www.notion.so/twreporter/20e8dbdca9328050a283d4d5c5797270?source=copy_link)
k6 do not support automatic migration, if the migration is required, we could write other script for it.
N/A

fix(cms): add recordCount for ImportRecord list

---

.changeset/great-spoons-trade.md
packages/frontend/src/components/search/instant-hit.tsx
packages/frontend/src/components/search/instant-hits.tsx

fix(frontend): add link for instant hits

---

.changeset/fancy-feet-sip.md
.changeset/stupid-aliens-shout.md
packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore: bump version

---

.changeset/pre.json
.changeset/slow-parrots-obey.md
packages/frontend/CHANGELOG.md
packages/frontend/next.config.ts
packages/frontend/package.json
packages/frontend/src/utils/logger.ts
yarn.lock

fix(frontend): gcp pino logging

---

packages/frontend/src/components/sidebar/filter-modal/index.tsx
packages/frontend/src/components/sidebar/title-section.tsx

[[報導者觀測站] 側邊欄調整項目](https://www.notion.so/twreporter/2418dbdca932804ba36ae61809781367?source=copy_link)
N/A

fix(frontend): reset sidebar tab when tabs change & fix sidebar filter close unexpected

---

.github/workflows/dev-version-bump.yml
.github/workflows/master-version-bump.yml
.github/workflows/release-version-bump.yml
lerna.json

ci: use lerna publish

---

packages/frontend/src/components/dashboard/index.tsx
packages/frontend/src/components/header/index.tsx

[[觀測站defect] header在firefox瀏覽器會有顯示異常](https://www.notion.so/twreporter/defect-header-firefox-2508dbdca932802a8b9fc1f108102267?source=copy_link)
we could consider to add something like css polyfill to support other browsers
N/A

fix(frontend): style defects on firefox

---

packages/frontend/src/fetchers/server/legislator.ts

[[觀測站defect] 議題獨立頁發言摘要排序修正](https://www.notion.so/twreporter/defect-25d8dbdca932809ea305ff7cde1b0ded?source=copy_link)

fix(frontend): legislator speech order

---

packages/frontend/src/components/speech/index.tsx

[[hotfixed] 觀測站贊助box先移除十週年的超連結](https://www.notion.so/twreporter/hotfixed-box-2698dbdca93280bd88b0faeac38575c2?source=copy_link)

fix(frontend): close new donation box

---

packages/frontend/CHANGELOG.md
packages/frontend/package.json

chore: test on staging

---

packages/frontend/src/components/about/index.tsx

fix(frontend): close new donation box on about page
